services:
  database:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=products-database'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  service:
    image: mspr4-2025/products-service
    ports:
      - '8080'
    depends_on:
      - database